version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: "sqlite:3.36"
    volumes:
      - db_data:/data/db
volumes:
  db_data: